version: "3"

services:
  mysqldb:
    image: mysql:5.6
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    links:
      - api
  api:
    container_name: api
    image: simpleapi-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    restart: always
