version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    links:
      - api
  api:
    container_name: api
    image: simpleapi-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    restart: always
